import { useEffect, useState } from 'react';
const BASE='https://pmjachoteyeviwwzotks.supabase.co/functions/v1/cars24-public-api';
type Props={type:string;make:string;model:string};
type HistoryRow={uid:string;vin?:string;auction?:string;auction_lot_id?:string;status?:string;displayed_date_utc?:string;currency?:string;final_bid_amount?:number|string;vehicle_title?:string;model_year?:number;odometer_miles?:number;primary_damage?:string;source_url?:string};
const money=(v:unknown)=>v!==null&&v!==undefined?`$${Number(v).toLocaleString('en-US')}`:'—';
const date=(v?:string)=>v?new Date(v).toLocaleDateString('uk-UA'):'—';

export default function ModelDetail({type,make,model}:Props){
  const [data,setData]=useState<any>(null);const [history,setHistory]=useState<HistoryRow[]>([]);const [coverage,setCoverage]=useState<any>(null);const [error,setError]=useState('');
  useEffect(()=>{let live=true;(async()=>{try{const r=await fetch(`${BASE}/model?type=${encodeURIComponent(type)}&make=${encodeURIComponent(make)}&model=${encodeURIComponent(model)}`);const j=await r.json();if(!r.ok)throw new Error(j?.error||'Помилка');if(!live)return;setData(j.data);if(j.data?.model_id){const hr=await fetch(`${BASE}/history?model_id=${j.data.model_id}`);const hj=await hr.json();if(live&&hr.ok){setHistory(Array.isArray(hj.data)?hj.data:[]);setCoverage(hj.coverage||null);}}}catch(e){if(live)setError(String((e as Error).message||e));}})();return()=>{live=false}},[type,make,model]);
  if(error)return <div className="modelState">Не вдалося завантажити характеристики.</div>;
  if(!data)return <div className="modelState">Завантажую перевірені дані Cars24…</div>;
  const gens=Array.isArray(data.generations)?data.generations:[];
  return <div>
    {data.image_url&&<div className="heroImage"><img src={data.image_url} alt={`${data.make_name} ${data.model_name}`} /></div>}
    <div className="modelFacts"><div><span>Роки моделі</span><b>{data.year_from||'—'} — {data.year_to||'дотепер'}</b></div><div><span>Поколінь у базі</span><b>{gens.length}</b></div><div><span>Тип</span><b>{data.vehicle_type==='moto'?'Мото':'Авто'}</b></div></div>

    {history.length>0&&<section className="auctionHistory"><div className="sectionLabel">Аукціонна історія Cars24</div><div className="historyHead"><div><h2>Реальні продажі цієї моделі</h2><p>Не прогноз і не середня ціна — конкретні лоти з VIN, датою та фінальною ставкою.</p></div><span>{coverage?.status==='partial_preview_slice'?'Поки часткове покриття':'Cars24 Data'}</span></div><div className="historyGrid">{history.slice(0,12).map(h=><a href={h.source_url||'#'} target="_blank" rel="noreferrer" className="saleCard" key={h.uid}><div className="saleTop"><span>{h.model_year||'—'}</span><b>{money(h.final_bid_amount)}</b></div><strong>{h.auction||'Аукціон'} · Lot {h.auction_lot_id||'—'}</strong><p>{[h.primary_damage,h.odometer_miles?`${Number(h.odometer_miles).toLocaleString('en-US')} mi`:null].filter(Boolean).join(' · ')}</p><div className="saleVin">{h.vin||'VIN не вказаний'} <span>{date(h.displayed_date_utc)}</span></div></a>)}</div></section>}

    {gens.map((g:any)=><section className="generation" key={g.id}><div className="genHead"><div><span>Покоління</span><h2>{g.generation_name||g.platform_code||`${g.year_from||''}–${g.year_to||'дотепер'}`}</h2></div><strong>{g.year_from||'—'} — {g.year_to||'дотепер'}</strong></div>
      <div className="specGrid">{[['Кузов',g.body_style],['Клас',g.vehicle_class],['Місця',g.seats],['Двері',g.doors],['Довжина',g.specs?.length_mm?`${g.specs.length_mm} мм`:null],['Ширина',g.specs?.width_mm?`${g.specs.width_mm} мм`:null],['Висота',g.specs?.height_mm?`${g.specs.height_mm} мм`:null],['Колісна база',g.specs?.wheelbase_mm?`${g.specs.wheelbase_mm} мм`:null],['Кліренс',g.specs?.ground_clearance_mm?`${g.specs.ground_clearance_mm} мм`:null],['Багажник',g.specs?.cargo_l?`${g.specs.cargo_l} л`:null],['Буксирування',g.specs?.towing_capacity_kg?`${g.specs.towing_capacity_kg} кг`:null]].filter(([,v])=>v).map(([l,v])=><div key={String(l)}><span>{l}</span><b>{String(v)}</b></div>)}</div>
      {!!g.powertrains?.length&&<div className="powertrains">{g.powertrains.map((p:any)=><div className="power" key={p.id}><b>{p.name||p.fuel_type||'Силова установка'}</b><p>{[p.engine_displacement_l?`${p.engine_displacement_l} л`:null,p.horsepower_hp?`${p.horsepower_hp} к.с.`:null,p.drivetrain,p.transmission,p.battery_kwh?`${p.battery_kwh} кВт·год`:null].filter(Boolean).join(' · ')}</p></div>)}</div>}
      {!!g.sources?.length&&<details className="sources"><summary>Джерела характеристик · {g.sources.length}</summary><div>{g.sources.slice(0,12).map((s:any,i:number)=><a href={s.source_url} target="_blank" rel="noreferrer" key={`${s.source_url}-${i}`}>{s.source_name||'Джерело'}{s.field_name?` · ${s.field_name}`:''}</a>)}</div></details>}
    </section>)}
    <style>{`.modelState{padding:24px;border:1px solid #d9d6ce;border-radius:18px;background:#fffdf8;color:#6b7280}.heroImage{border-radius:24px;overflow:hidden;background:#e9e6df;max-height:520px}.heroImage img{width:100%;height:100%;max-height:520px;object-fit:cover}.modelFacts{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:16px 0}.modelFacts>div,.specGrid>div{background:#fffdf8;border:1px solid #d9d6ce;border-radius:14px;padding:14px}.modelFacts span,.specGrid span,.genHead span{display:block;font-size:10px;text-transform:uppercase;letter-spacing:.1em;color:#6b7280;font-weight:850;margin-bottom:4px}.auctionHistory{margin:36px 0}.sectionLabel{font-size:11px;text-transform:uppercase;letter-spacing:.12em;color:#2563eb;font-weight:900}.historyHead{display:flex;justify-content:space-between;gap:18px;align-items:start;margin:5px 0 14px}.historyHead h2{font-size:30px;margin:0 0 5px}.historyHead p{color:#6b7280;margin:0}.historyHead>span{font-size:11px;padding:6px 9px;border-radius:20px;background:#e0e7ff;color:#3730a3;white-space:nowrap;font-weight:800}.historyGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.saleCard{padding:14px;background:#fffdf8;border:1px solid #d9d6ce;border-radius:15px;display:grid;gap:5px}.saleTop{display:flex;justify-content:space-between;color:#6b7280}.saleTop b{font-size:20px;color:#111827}.saleCard>strong{font-size:13px}.saleCard p{margin:0;color:#b45309;font-size:11px}.saleVin{font-family:monospace;font-size:10px;color:#6b7280;display:flex;justify-content:space-between;gap:8px}.generation{margin-top:28px;background:#fffdf8;border:1px solid #d9d6ce;border-radius:22px;padding:22px}.genHead{display:flex;justify-content:space-between;gap:16px;align-items:start}.genHead h2{font-size:28px;margin:4px 0 18px}.specGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.powertrains{margin-top:14px;display:grid;gap:8px}.power{padding:14px;background:#f4f1e9;border-radius:14px}.power p{margin:5px 0 0;color:#6b7280}.sources{margin-top:12px;border-top:1px solid #e5e1d8;padding-top:10px}.sources summary{cursor:pointer;color:#6b7280;font-size:12px;font-weight:800}.sources div{display:flex;gap:7px;flex-wrap:wrap;margin-top:9px}.sources a{font-size:11px;background:#f4f1e9;border-radius:8px;padding:6px 8px;color:#475569}@media(max-width:900px){.historyGrid{grid-template-columns:repeat(2,1fr)}}@media(max-width:700px){.modelFacts{grid-template-columns:1fr}.specGrid{grid-template-columns:1fr 1fr}.genHead,.historyHead{display:block}.historyHead>span{display:inline-block;margin-top:9px}}@media(max-width:500px){.historyGrid{grid-template-columns:1fr}}`}</style>
  </div>;
}
