import { useState } from 'react';

type Row=Record<string,unknown>;
type ApiResult={vin:string;decoded?:Row;history?:Row[];recalls?:Row[];meta?:Row};
const API='https://pmjachoteyeviwwzotks.supabase.co/functions/v1/cars24-vin-api';
const val=(o:Row|undefined,k:string)=>typeof o?.[k]==='string'||typeof o?.[k]==='number'?String(o[k]):'';
const clean=(v:string)=>v && !['Not Applicable','N/A','0','null'].includes(v.trim())?v:'';
const fmtMoney=(v:unknown)=>v!==null&&v!==undefined&&v!==''?`$${Number(v).toLocaleString('en-US')}`:'—';
const fmtDate=(v:unknown)=>{if(!v)return '—';const d=new Date(String(v));return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString('uk-UA')};

const groups:[string,[string,string][]][]=[
  ['Двигун і трансмісія', [['Потужність, к.с.','EngineHP'],['Потужність, кВт','EngineKW'],['Модель двигуна','EngineModel'],['Виробник двигуна','EngineManufacturer'],['Конфігурація','EngineConfiguration'],['Цикли','EngineCycles'],['Газорозподіл','ValveTrainDesign'],['Турбо','Turbo'],['Охолодження','CoolingType'],['Упорскування','FuelInjectionType'],['Додаткове пальне','FuelTypeSecondary'],['КПП','TransmissionStyle'],['Передач','TransmissionSpeeds']]],
  ['Електрифікація', [['Рівень електрифікації','ElectrificationLevel'],['Тип батареї','BatteryType'],['Батарея','BatteryInfo'],['Ємність, кВт·год','BatteryKWh'],['Ємність до, кВт·год','BatteryKWh_to'],['Напруга, В','BatteryV'],['Зарядний пристрій','ChargerLevel'],['Потужність заряджання, кВт','ChargerPowerKW'],['Електропривід','EVDriveUnit']]],
  ['Безпека та ADAS', [['ABS','ABS'],['ESC','ESC'],['Traction Control','TractionControl'],['TPMS','TPMS'],['Адаптивний круїз','AdaptiveCruiseControl'],['Контроль сліпих зон','BlindSpotMon'],['Попередження зіткнення','ForwardCollisionWarning'],['Контроль смуги','LaneDepartureWarning'],['Утримання смуги','LaneKeepSystem'],['Центрування у смузі','LaneCenteringAssistance'],['AEB пішоходи','PedestrianAutomaticEmergencyBraking'],['AEB ззаду','RearAutomaticEmergencyBraking'],['Перехресний рух ззаду','RearCrossTrafficAlert'],['Паркувальний асистент','ParkAssist'],['Камера заднього виду','RearVisibilitySystem'],['Безключовий запуск','KeylessIgnition']]],
  ['Виробництво та ідентифікація', [['Vehicle Descriptor','VehicleDescriptor'],['Серія','Series'],['Серія 2','Series2'],['Комплектація','Trim'],['Комплектація 2','Trim2'],['Завод — місто','PlantCity'],['Завод — штат','PlantState'],['Завод — країна','PlantCountry'],['Завод / компанія','PlantCompanyName'],['Ринок призначення','DestinationMarket'],['GVWR','GVWR'],['GCWR','GCWR'],['Двері','Doors'],['Місця','Seats'],['Рядів сидінь','SeatRows'],['Коліс','Wheels']]],
  ['Мотоцикл', [['Тип шасі','MotorcycleChassisType'],['Підвіска','MotorcycleSuspensionType'],['Тип кастомного мото','CustomMotorcycleType'],['Додаткова інформація','OtherMotorcycleInfo'],['Wheelie mitigation','WheelieMitigation'],['Комбінована гальмівна система','CombinedBrakingSystem']]],
];

export default function VinDecoder(){
  const [vin,setVin]=useState(''); const [data,setData]=useState<ApiResult|null>(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
  async function submit(e:{preventDefault:()=>void}){e.preventDefault();const input=vin.trim().toUpperCase();if(!/^[A-HJ-NPR-Z0-9]{17}$/.test(input)){setError('Введіть коректний VIN із 17 символів.');return;}setLoading(true);setError('');setData(null);try{const r=await fetch(`${API}?vin=${encodeURIComponent(input)}`);const j=await r.json();if(!r.ok)throw new Error(j?.error||'Помилка декодування');setData(j);}catch(e){setError(e instanceof Error?e.message:'Помилка запиту');}finally{setLoading(false)}}
  const d=data?.decoded;
  const primary=[['Марка',val(d,'Make')],['Модель',val(d,'Model')],['Рік',val(d,'ModelYear')],['Виробник',val(d,'Manufacturer')],['Кузов',val(d,'BodyClass')],['Тип',val(d,'VehicleType')],['Пальне',val(d,'FuelTypePrimary')],['Привід',val(d,'DriveType')],['Двигун',val(d,'DisplacementL')?`${val(d,'DisplacementL')} л`:val(d,'EngineModel')],['Циліндри',val(d,'EngineCylinders')],['Завод', [val(d,'PlantCity'),val(d,'PlantCountry')].filter(Boolean).join(', ')]].filter(([,v])=>clean(v));
  const visibleGroups=groups.map(([name,items])=>[name,items.map(([label,key])=>[label,clean(val(d,key))] as [string,string]).filter(([,v])=>v)] as const).filter(([,items])=>items.length);
  return <div className="vinTool">
    <form onSubmit={submit} className="vinForm"><input value={vin} onChange={e=>setVin(e.target.value.toUpperCase())} maxLength={17} placeholder="Наприклад, SMTD51HG8NTAU3229" aria-label="VIN"/><button disabled={loading}>{loading?'Перевіряю…':'Розшифрувати VIN'}</button></form>
    {error&&<p className="vinError">{error}</p>}
    {data&&<div className="vinResult">
      <div className="vinIdentity"><div><span>VIN</span><strong>{data.vin}</strong></div><div className="vinCounts"><b>{data.history?.length||0}</b> записів Cars24 <i>·</i> <b>{data.recalls?.length||0}</b> відкликань NHTSA</div></div>
      <div className="primaryGrid">{primary.map(([l,v])=><div key={l}><span>{l}</span><b>{v}</b></div>)}</div>
      {!!data.history?.length&&<section className="history"><div className="sectionKicker">Історія Cars24</div><h3>Цей VIN уже є в наших аукціонних даних</h3><div className="historyList">{data.history.map((h,i)=><a key={i} href={String(h.source_url||'#')} target="_blank" rel="noreferrer" className="historyRow"><div><b>{String(h.vehicle_title||[h.model_year,h.make,h.model].filter(Boolean).join(' ')||data.vin)}</b><span>{String(h.auction||'Аукціон')} · Lot {String(h.auction_lot_id||h.lot_id||'—')}</span></div><div className="historyNums"><b>{fmtMoney(h.final_bid_amount||h.final_bid)}</b><span>{fmtDate(h.displayed_date_utc||h.sale_date_utc||h.sale_date)}</span></div></a>)}</div></section>}
      {!!data.recalls?.length&&<section className="recalls"><div className="sectionKicker">NHTSA recalls</div><h3>Відкликання для цієї моделі та року</h3><p>Публічний API NHTSA не підтверджує, чи виконана конкретна кампанія саме на цьому VIN.</p><div className="recallList">{data.recalls.slice(0,8).map((r,i)=><div key={i}><b>{String(r.Component||r.component||'Кампанія')}</b><span>{String(r.Summary||r.summary||r.Consequence||'')}</span></div>)}</div></section>}
      {visibleGroups.map(([name,items])=><details className="tech" key={name}><summary>{name}<span>{items.length}</span></summary><div className="techGrid">{items.map(([l,v])=><div key={l}><span>{l}</span><b>{v}</b></div>)}</div></details>)}
    </div>}
    <style>{`.vinForm{display:flex;gap:10px;flex-wrap:wrap}.vinForm input{flex:1 1 330px;padding:15px 16px;border:1px solid #d9d6ce;border-radius:14px;font-family:monospace;font-size:16px;background:#fff}.vinForm button{border:0;border-radius:14px;padding:14px 20px;background:#2563eb;color:#fff;font-weight:900;cursor:pointer}.vinForm button:disabled{opacity:.6}.vinError{color:#b91c1c;margin:14px 0 0}.vinResult{margin-top:24px}.vinIdentity{display:flex;justify-content:space-between;gap:20px;align-items:end;flex-wrap:wrap;padding-bottom:18px;border-bottom:1px solid #e5e1d8}.vinIdentity span,.primaryGrid span,.techGrid span{display:block;color:#6b7280;font-size:11px;font-weight:800;margin-bottom:4px}.vinIdentity strong{font-family:monospace;font-size:19px}.vinCounts{color:#475569}.vinCounts i{font-style:normal;margin:0 7px;color:#bbb}.primaryGrid,.techGrid{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:9px;margin-top:16px}.primaryGrid>div,.techGrid>div{border:1px solid #d9d6ce;border-radius:14px;padding:13px;background:#fff}.history,.recalls{margin-top:26px}.sectionKicker{font-size:11px;text-transform:uppercase;letter-spacing:.12em;color:#2563eb;font-weight:900}.history h3,.recalls h3{font-size:24px;margin:5px 0 12px}.historyList{display:grid;gap:8px}.historyRow{display:flex;justify-content:space-between;gap:14px;padding:14px;border-radius:14px;background:#eff6ff;border:1px solid #dbeafe}.historyRow div{display:grid;gap:3px}.historyRow span{font-size:12px;color:#64748b}.historyNums{text-align:right;flex-shrink:0}.recalls>p{color:#64748b}.recallList{display:grid;gap:8px}.recallList>div{padding:14px;border:1px solid #fed7aa;background:#fff7ed;border-radius:14px;display:grid;gap:5px}.recallList span{font-size:13px;color:#6b7280;line-height:1.45}.tech{margin-top:12px;border:1px solid #d9d6ce;border-radius:16px;background:#faf8f3;overflow:hidden}.tech summary{list-style:none;cursor:pointer;padding:15px 16px;font-weight:900;display:flex;justify-content:space-between}.tech summary::-webkit-details-marker{display:none}.tech summary span{background:#e5e7eb;padding:2px 8px;border-radius:20px;color:#6b7280;font-size:12px}.techGrid{padding:0 14px 14px;margin-top:0}@media(max-width:600px){.historyRow{display:grid}.historyNums{text-align:left;display:flex!important;justify-content:space-between}}`}</style>
  </div>;
}
